apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.2
    path: /nfs-storage
